# Configuration commun à tous les environnements
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${PORT:8081}

jo:
  jwtSecret: ${JWT_SECRET}
  jwtExpirationInMs: 86400000

frontUrl: ${FRONT_URL}

admin:
  firstname: ${ADMIN_FIRSTNAME}
  lastname: ${ADMIN_LASTNAME}
  username: ${ADMIN_USERNAME}
  password: ${ADMIN_PASSWORD}


cart:
  item:
    expiration-duration: ${ITEM_EXPIRATION_DURATION}