# Configuration de production Railway
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    virtual-host: ${RABBITMQ_VIRTUAL_HOST}
    ssl:
      enabled: ${RABBITMQ_SSL_ENABLED}
  jpa:
    show-sql: false
    hibernate:
      # update : pour la démo — passer à validate en production réelle
      ddl-auto: update
  sql:
    init:
      # always : exécute data.sql à chaque démarrage
      # Passer à never si les données de démo ne sont plus nécessaires
      mode: never