# Configuration commune à tous les environnements
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
server:
  port: ${PORT:8081}
jo:
  jwtSecret: ${JWT_SECRET}
  jwtExpirationInMs: 86400000
frontUrl: ${FRONT_URL}
admin:
  firstname: ${ADMIN_FIRSTNAME}
  lastname: ${ADMIN_LASTNAME}
  username: ${ADMIN_USERNAME}
  password: ${ADMIN_PASSWORD}
cart:
  item:
    item_expiration_duration: ${ITEM_EXPIRATION_DURATION}